import { auth, db } from './firebase.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, serverTimestamp, setDoc, updateDoc, query, where } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let admin=null,sessions=[],homeworks=[],submissions=[],students=[];
let stops=[];
const $=id=>document.getElementById(id);

function isoFromLocal(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString();}
function localValue(iso){if(!iso)return'';const d=new Date(iso);if(Number.isNaN(d.getTime()))return'';const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function matchesAudience(student,item){if(item.level&&item.level!=='Tous'&&student.level!==item.level)return false;if(item.level==='1ère'||student.level==='1ère')return true;return !item.section||item.section==='Toutes'||item.section==='Tronc commun'||student.section===item.section;}
async function notifyAudience(item,title,body,type){const recipients=students.filter(s=>s.status==='approved'&&matchesAudience(s,item));await Promise.all(recipients.map(s=>addDoc(collection(db,'notifications'),{userId:s.id,title,body,type,read:false,createdBy:admin.uid,createdAt:serverTimestamp(),createdAtIso:new Date().toISOString()}).catch(console.warn)));}

function renderSessions(){
  $('adminSessionStat').textContent=sessions.length;
  const shell=$('adminSessionList');
  if(!sessions.length){shell.innerHTML='<p class="panel-subtitle">Aucune séance programmée.</p>';return;}
  shell.innerHTML=sessions.sort((a,b)=>new Date(a.startAtIso)-new Date(b.startAtIso)).map(s=>`<article class="v4-admin-item"><div><div class="course-meta"><span>${esc(s.level)}</span><span>${esc(s.section)}</span><span>T${esc(s.trimester||'1')}</span></div><h3>${esc(s.title)}</h3><p>📅 ${new Date(s.startAtIso).toLocaleString('fr-FR')}</p></div><div class="v4-admin-actions"><button class="btn secondary" data-edit-session="${esc(s.id)}">Modifier</button><button class="btn danger" data-delete-session="${esc(s.id)}">Supprimer</button></div></article>`).join('');
  shell.querySelectorAll('[data-edit-session]').forEach(b=>b.onclick=()=>editSession(b.dataset.editSession));
  shell.querySelectorAll('[data-delete-session]').forEach(b=>b.onclick=()=>deleteSession(b.dataset.deleteSession));
}
function resetSession(){ $('sessionForm').reset();$('sessionEditId').value='';$('sessionTrimester').value='1';$('cancelSessionEdit').classList.add('hidden'); }
function editSession(id){const s=sessions.find(x=>x.id===id);if(!s)return;$('sessionEditId').value=id;$('sessionTitle').value=s.title||'';$('sessionLevel').value=s.level||'Tous';$('sessionSection').value=s.section||'Toutes';$('sessionTrimester').value=String(s.trimester||'1');$('sessionDateTime').value=localValue(s.startAtIso);$('sessionMeetUrl').value=s.meetUrl||'';$('sessionDescription').value=s.description||'';$('cancelSessionEdit').classList.remove('hidden');$('sessionForm').scrollIntoView({behavior:'smooth',block:'center'});}
async function deleteSession(id){if(!confirm('Supprimer cette séance ?'))return;try{await deleteDoc(doc(db,'sessions',id));}catch(e){console.error(e);alert('Suppression impossible.');}}

function renderHomework(){
  $('adminHomeworkStat').textContent=homeworks.length;
  const shell=$('adminHomeworkList');
  if(!homeworks.length){shell.innerHTML='<p class="panel-subtitle">Aucun devoir publié.</p>';return;}
  const counts=new Map();submissions.forEach(s=>counts.set(s.homeworkId,(counts.get(s.homeworkId)||0)+1));
  shell.innerHTML=homeworks.sort((a,b)=>new Date(a.dueAtIso)-new Date(b.dueAtIso)).map(h=>`<article class="v4-admin-item"><div><div class="course-meta"><span>${esc(h.level)}</span><span>${esc(h.section)}</span><span>T${esc(h.trimester||'1')}</span><span>${esc(h.domain||'')}</span></div><h3>${esc(h.title)}</h3><p>⏳ ${new Date(h.dueAtIso).toLocaleString('fr-FR')} · 📥 ${counts.get(h.id)||0} rendu(s)</p></div><div class="v4-admin-actions"><button class="btn secondary" data-submissions="${esc(h.id)}">Rendus</button><button class="btn secondary" data-edit-homework="${esc(h.id)}">Modifier</button><button class="btn danger" data-delete-homework="${esc(h.id)}">Supprimer</button></div></article>`).join('');
  shell.querySelectorAll('[data-submissions]').forEach(b=>b.onclick=()=>showSubmissions(b.dataset.submissions));
  shell.querySelectorAll('[data-edit-homework]').forEach(b=>b.onclick=()=>editHomework(b.dataset.editHomework));
  shell.querySelectorAll('[data-delete-homework]').forEach(b=>b.onclick=()=>deleteHomework(b.dataset.deleteHomework));
}
function resetHomework(){ $('homeworkForm').reset();$('homeworkEditId').value='';$('homeworkTrimester').value='1';$('cancelHomeworkEdit').classList.add('hidden'); }
function editHomework(id){const h=homeworks.find(x=>x.id===id);if(!h)return;$('homeworkEditId').value=id;$('homeworkTitle').value=h.title||'';$('homeworkLevel').value=h.level||'Tous';$('homeworkSection').value=h.section||'Toutes';$('homeworkTrimester').value=String(h.trimester||'1');$('homeworkDomain').value=h.domain||'';$('homeworkDueAt').value=localValue(h.dueAtIso);$('homeworkResourceUrl').value=h.resourceUrl||'';$('homeworkDescription').value=h.description||'';$('cancelHomeworkEdit').classList.remove('hidden');$('homeworkForm').scrollIntoView({behavior:'smooth',block:'center'});}
async function deleteHomework(id){if(!confirm('Supprimer ce devoir ? Les rendus existants ne seront pas supprimés automatiquement.'))return;try{await deleteDoc(doc(db,'homework',id));}catch(e){console.error(e);alert('Suppression impossible.');}}

function showSubmissions(homeworkId){const hw=homeworks.find(h=>h.id===homeworkId),list=submissions.filter(s=>s.homeworkId===homeworkId);$('submissionPanel').classList.remove('hidden');$('submissionPanelTitle').textContent=hw?.title||'Devoir';const shell=$('submissionList');if(!list.length){shell.innerHTML='<div class="dashboard-empty compact"><span>📭</span><p>Aucun rendu pour le moment.</p></div>';}else{shell.innerHTML=list.map(s=>`<article class="submission-item"><div class="submission-student"><strong>${esc(s.studentName||s.studentEmail||'Élève')}</strong><small>${esc(s.studentEmail||'')}</small><span>${s.submittedAtIso?new Date(s.submittedAtIso).toLocaleString('fr-FR'):'—'}</span></div><div class="submission-answer"><p>${esc(s.answerText||'Aucune réponse texte')}</p>${s.answerUrl?`<a href="${esc(s.answerUrl)}" target="_blank" rel="noopener">🔗 Ouvrir le travail</a>`:''}</div><form class="grade-form" data-submission-id="${esc(s.id)}"><label>Note /20<input type="number" min="0" max="20" step="0.25" value="${esc(s.grade??'')}"></label><label>Commentaire<textarea rows="2" maxlength="600">${esc(s.feedback||'')}</textarea></label><button class="btn primary" type="submit">Enregistrer correction</button></form></article>`).join('');shell.querySelectorAll('.grade-form').forEach(f=>f.onsubmit=gradeSubmission);}$('submissionPanel').scrollIntoView({behavior:'smooth',block:'start'});}
async function gradeSubmission(e){e.preventDefault();const form=e.currentTarget,id=form.dataset.submissionId,[grade,feedback]=form.querySelectorAll('input,textarea');try{await updateDoc(doc(db,'homeworkSubmissions',id),{grade:grade.value===''?null:Number(grade.value),feedback:feedback.value.trim(),status:'graded',gradedAt:serverTimestamp(),gradedAtIso:new Date().toISOString(),gradedBy:admin.uid});const sub=submissions.find(s=>s.id===id);if(sub){sub.grade=grade.value===''?null:Number(grade.value);sub.feedback=feedback.value.trim();sub.status='graded';}const hw=homeworks.find(h=>h.id===sub?.homeworkId);if(sub?.userId)await addDoc(collection(db,'notifications'),{userId:sub.userId,title:'Devoir corrigé ✅',body:`Ton devoir « ${hw?.title||'Ben-Learning'} » a été corrigé${grade.value!==''?` : ${grade.value}/20`:''}.`,type:'homework',read:false,createdBy:admin.uid,createdAt:serverTimestamp(),createdAtIso:new Date().toISOString()});alert('Correction enregistrée ✅');showSubmissions(sub?.homeworkId);}catch(err){console.error(err);alert('Impossible d’enregistrer la correction.');}}

$('sessionForm')?.addEventListener('submit',async e=>{e.preventDefault();const id=$('sessionEditId').value||`session-${Date.now()}`;const item={title:$('sessionTitle').value.trim(),level:$('sessionLevel').value,section:$('sessionSection').value,trimester:$('sessionTrimester').value,startAtIso:isoFromLocal($('sessionDateTime').value),meetUrl:$('sessionMeetUrl').value.trim(),description:$('sessionDescription').value.trim(),createdBy:admin.uid,updatedAt:serverTimestamp(),updatedAtIso:new Date().toISOString()};try{await setDoc(doc(db,'sessions',id),item,{merge:true});if(!$('sessionEditId').value)await notifyAudience(item,'Nouvelle séance programmée 📅',`Une nouvelle séance « ${item.title} » est programmée le ${new Date(item.startAtIso).toLocaleString('fr-FR')}.`,'session');resetSession();}catch(err){console.error(err);alert('Impossible d’enregistrer la séance.');}});
$('homeworkForm')?.addEventListener('submit',async e=>{e.preventDefault();const id=$('homeworkEditId').value||`homework-${Date.now()}`;const item={title:$('homeworkTitle').value.trim(),level:$('homeworkLevel').value,section:$('homeworkSection').value,trimester:$('homeworkTrimester').value,domain:$('homeworkDomain').value.trim(),dueAtIso:isoFromLocal($('homeworkDueAt').value),resourceUrl:$('homeworkResourceUrl').value.trim(),description:$('homeworkDescription').value.trim(),createdBy:admin.uid,updatedAt:serverTimestamp(),updatedAtIso:new Date().toISOString()};try{await setDoc(doc(db,'homework',id),item,{merge:true});if(!$('homeworkEditId').value)await notifyAudience(item,'Nouveau devoir 📝',`Le devoir « ${item.title} » est disponible. Date limite : ${new Date(item.dueAtIso).toLocaleString('fr-FR')}.`,'homework');resetHomework();}catch(err){console.error(err);alert('Impossible d’enregistrer le devoir.');}});
$('cancelSessionEdit')?.addEventListener('click',resetSession);$('cancelHomeworkEdit')?.addEventListener('click',resetHomework);$('closeSubmissionPanel')?.addEventListener('click',()=>$('submissionPanel').classList.add('hidden'));

onAuthStateChanged(auth,async user=>{if(!user)return;const snap=await getDoc(doc(db,'users',user.uid)).catch(()=>null);if(!snap?.exists()||snap.data().role!=='admin')return;admin=user;try{const uSnap=await getDocs(query(collection(db,'users'),where('role','==','student')));students=uSnap.docs.map(d=>({id:d.id,...d.data()}));stops.push(onSnapshot(collection(db,'sessions'),snap=>{sessions=snap.docs.map(d=>({id:d.id,...d.data()}));renderSessions();}));stops.push(onSnapshot(collection(db,'homework'),snap=>{homeworks=snap.docs.map(d=>({id:d.id,...d.data()}));renderHomework();}));stops.push(onSnapshot(collection(db,'homeworkSubmissions'),snap=>{submissions=snap.docs.map(d=>({id:d.id,...d.data()}));renderHomework();const panel=$('submissionPanel');if(panel&&!panel.classList.contains('hidden')){const current=$('submissionPanelTitle').textContent;const hw=homeworks.find(h=>h.title===current);if(hw)showSubmissions(hw.id);}}));}catch(e){console.error('Modules V4 admin indisponibles',e);}});
window.addEventListener('beforeunload',()=>stops.forEach(fn=>fn?.()));
