const REPLACED_COURSE_IDS=new Set(['premiere-production-numerique-2d-3d','premiere-production-numerique-modelisation-3d-smart-cross-road','5']);
(async()=>{
const messages=document.getElementById('aiMessages'),form=document.getElementById('aiForm'),input=document.getElementById('aiInput'),ctx=document.getElementById('aiContext');const session=JSON.parse(localStorage.getItem('bl_session')||'null');if(!session){location.href='login.html';return;}const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));let data={courses:[],progress:[],quiz:[],sessions:[],homework:[],submissions:[]};
function relevant(x){if(x.level&&x.level!==session.level&&x.level!=='Tous')return false;if(session.level==='1ère')return true;return !x.section||x.section==='Toutes'||x.section==='Tronc commun'||x.section===session.section;}
function add(role,text){messages.insertAdjacentHTML('beforeend',`<div class="ai-message ${role}"><span>${role==='bot'?'🤖':'👤'}</span><div><strong>${role==='bot'?'Ben IA':esc(session.name||'Moi')}</strong><p>${esc(text).replace(/\n/g,'<br>')}</p></div></div>`);messages.scrollTop=messages.scrollHeight;}
function courseDoneIds(){return new Set(data.progress.map(p=>String(p.courseId)));}
function nextCourse(){const done=courseDoneIds();return data.courses.filter(relevant).find(c=>!done.has(String(c.id)));}
function nextSession(){return data.sessions.filter(relevant).filter(s=>new Date(s.startAtIso)>new Date()).sort((a,b)=>new Date(a.startAtIso)-new Date(b.startAtIso))[0];}
function pendingHomework(){const submitted=new Set(data.submissions.map(s=>s.homeworkId));return data.homework.filter(relevant).filter(h=>!submitted.has(h.id)).sort((a,b)=>new Date(a.dueAtIso)-new Date(b.dueAtIso));}
function weakScore(){if(!data.quiz.length)return null;return Math.round(data.quiz.reduce((a,q)=>a+Number(q.score||0),0)/data.quiz.length);}
function answer(q){const t=q.toLowerCase();const next=nextCourse(),meet=nextSession(),hw=pendingHomework(),avg=weakScore();
 if(/devoir|travail|rendre/.test(t)){return hw.length?`Tu as ${hw.length} devoir(s) à rendre. Le plus proche est « ${hw[0].title} », prévu pour le ${new Date(hw[0].dueAtIso).toLocaleString('fr-FR')}. Ouvre la page Devoirs pour envoyer ta réponse.`:'Tu n’as actuellement aucun devoir en attente. Profite-en pour avancer dans tes cours ou faire un quiz.';}
 if(/séance|seance|meet|planning|cours en ligne/.test(t)){return meet?`Ta prochaine séance est « ${meet.title} » le ${new Date(meet.startAtIso).toLocaleString('fr-FR',{weekday:'long',day:'2-digit',month:'long',hour:'2-digit',minute:'2-digit'})}. Tu trouveras le bouton Google Meet dans la page Séances.`:'Aucune séance future n’est encore programmée pour ton parcours.';}
 if(/prochain|continuer|cours suivant/.test(t)){return next?`Je te conseille de continuer avec « ${next.title} » (${next.domain||'Informatique'}, trimestre ${next.trimester||1}). ${next.description||''}`:'Bravo : tu as terminé tous les cours actuellement disponibles pour ton parcours.';}
 if(/révis|revis|plan|semaine|priorit/.test(t)){let lines=[];if(next)lines.push(`1. Commence par « ${next.title} ».`);if(avg!==null)lines.push(`2. Ta moyenne actuelle aux quiz est ${avg}%. ${avg<70?'Prévois une nouvelle tentative après révision.':'Consolide avec des exercices ciblés.'}`);if(hw.length)lines.push(`3. Priorité au devoir « ${hw[0].title} » avant sa date limite.`);if(meet)lines.push(`4. Prépare les questions à poser avant la séance « ${meet.title} ».`);return lines.length?lines.join('\n'):'Commence par consulter ton catalogue de cours, puis réalise un quiz pour que je puisse te proposer un plan plus précis.';}
 const keyword=data.courses.filter(relevant).find(c=>t.includes(String(c.domain||'').toLowerCase())||t.includes(String(c.title||'').toLowerCase().split('—')[0].trim()));if(keyword){return `Pour « ${keyword.title} » : ${keyword.description||'consulte le cours.'} Les chapitres principaux sont : ${(keyword.chapters||[]).slice(0,5).join(', ')||keyword.chapter||'contenu à consulter'}. Je te conseille de lire le cours, faire les exercices puis valider avec un quiz.`;}
 return `Pour ton parcours ${session.level}${session.section?` ${session.section}`:''}, je peux t’aider à choisir quoi réviser, trouver ton prochain cours, vérifier tes devoirs, ton planning Meet ou préparer un plan de révision. Essaie par exemple : « Que dois-je réviser ? »`;
}
async function load(){try{const [{db},fs]=await Promise.all([import('./firebase.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js')]);const seed=await fetch('data/courses.json').then(r=>r.json()).catch(()=>[]);const [cs,ps,qs,ss,hs,subs]=await Promise.all([fs.getDocs(fs.collection(db,'courses')),fs.getDocs(fs.query(fs.collection(db,'courseProgress'),fs.where('userId','==',session.uid))),fs.getDocs(fs.query(fs.collection(db,'quizResults'),fs.where('userId','==',session.uid))),fs.getDocs(fs.collection(db,'sessions')),fs.getDocs(fs.collection(db,'homework')),fs.getDocs(fs.query(fs.collection(db,'homeworkSubmissions'),fs.where('userId','==',session.uid)))]);const cloud=cs.docs.map(d=>({id:d.id,...d.data()})),map=new Map();[...seed,...cloud].forEach(c=>{if(!REPLACED_COURSE_IDS.has(String(c.id)))map.set(String(c.id),c);});data.courses=[...map.values()];data.progress=ps.docs.map(d=>d.data());data.quiz=qs.docs.map(d=>d.data());data.sessions=ss.docs.map(d=>({id:d.id,...d.data()}));data.homework=hs.docs.map(d=>({id:d.id,...d.data()}));data.submissions=subs.docs.map(d=>d.data());const eligible=data.courses.filter(relevant),done=courseDoneIds();ctx.innerHTML=`<div><span>🎓</span><b>${esc(session.level)} · ${esc(session.section||'Général')}</b></div><div><span>📚</span><b>${[...done].filter(id=>eligible.some(c=>String(c.id)===id)).length}/${eligible.length} cours terminés</b></div><div><span>📝</span><b>${data.quiz.length} quiz · ${weakScore()??0}% moyenne</b></div><div><span>📅</span><b>${nextSession()?'1 prochaine séance':'Aucune séance proche'}</b></div><div><span>📌</span><b>${pendingHomework().length} devoir(s) en attente</b></div>`;}catch(e){console.error(e);ctx.innerHTML='<p>Contexte partiellement indisponible. L’assistant peut quand même répondre avec les données locales.</p>';}}
form.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(!q)return;add('user',q);input.value='';setTimeout(()=>add('bot',answer(q)),180);});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.prompt;form.requestSubmit();}));await load();
})();
