(async()=>{
const shell=document.getElementById('homeworkList'),summary=document.getElementById('homeworkSummary');const session=JSON.parse(localStorage.getItem('bl_session')||'null');if(!session){location.href='login.html';return;}
document.querySelector('.section-heading p')?.insertAdjacentHTML('afterend',`<div class="student-scope-badge">🎓 ${session.level}${session.level==='1ère'?' · Tronc commun':session.section?` · ${session.section}`:''}</div>`);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));let homeworks=[],submissions=new Map(),db,fs;
function relevant(x){if(x.level&&x.level!==session.level&&x.level!=='Tous')return false;if(session.level==='1ère')return true;return !x.section||x.section==='Toutes'||x.section==='Tronc commun'||x.section===session.section;}
function due(x){const d=new Date(x.dueAtIso||0);return Number.isNaN(d.getTime())?new Date(0):d;}
function statusOf(h){const s=submissions.get(h.id);if(s)return s.status==='graded'?'graded':'submitted';return due(h)&&due(h)<new Date()?'late':'todo';}
function render(){const list=homeworks.filter(relevant).sort((a,b)=>due(a)-due(b));const todo=list.filter(h=>statusOf(h)==='todo').length,submitted=list.filter(h=>['submitted','graded'].includes(statusOf(h))).length;summary.innerHTML=`<div><b>${list.length}</b><span>Devoirs</span></div><div><b>${todo}</b><span>À rendre</span></div><div><b>${submitted}</b><span>Rendus</span></div>`;if(!list.length){shell.innerHTML='<div class="dashboard-empty"><span>📝</span><h3>Aucun devoir pour le moment</h3><p>Les nouveaux travaux apparaîtront ici.</p></div>';return;}shell.innerHTML=list.map(h=>{const s=submissions.get(h.id),st=statusOf(h),d=due(h);return `<article class="homework-card"><div class="homework-top"><div class="course-meta"><span>${esc(h.level)}</span><span>${esc(h.section||'Toutes')}</span><span>T${esc(h.trimester||'1')}</span><span>${esc(h.domain||'')}</span></div><span class="homework-status ${st}">${st==='graded'?'✅ Corrigé':st==='submitted'?'📤 Rendu':st==='late'?'⛔ En retard':'⏳ À rendre'}</span></div><h2>${esc(h.title)}</h2><p>${esc(h.description||'')}</p><div class="homework-deadline">📅 Date limite : <strong>${d.getTime()?d.toLocaleString('fr-FR',{day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Non définie'}</strong></div>${h.resourceUrl?`<a class="btn secondary" href="${esc(h.resourceUrl)}" target="_blank" rel="noopener">📎 Ouvrir le sujet</a>`:''}<form class="homework-submit-form" data-homework-id="${esc(h.id)}"><label>Ma réponse<textarea rows="3" maxlength="2500" placeholder="Écris une réponse ou un commentaire…">${esc(s?.answerText||'')}</textarea></label><label>Lien de mon travail (Google Drive, GitHub…)<input type="url" placeholder="https://…" value="${esc(s?.answerUrl||'')}"></label><button class="btn primary" type="submit">${s?'Mettre à jour mon rendu':'Envoyer mon devoir'}</button></form>${s?.grade!==undefined&&s?.grade!==null&&s?.grade!==''?`<div class="teacher-feedback"><strong>Note : ${esc(s.grade)}/20</strong><p>${esc(s.feedback||'')}</p></div>`:''}</article>`}).join('');document.querySelectorAll('.homework-submit-form').forEach(f=>f.addEventListener('submit',submitHomework));}
async function submitHomework(e){e.preventDefault();const form=e.currentTarget,id=form.dataset.homeworkId,btn=form.querySelector('button');const [ta,input]=form.querySelectorAll('textarea,input');if(!ta.value.trim()&&!input.value.trim()){alert('Ajoute une réponse ou un lien avant d’envoyer.');return;}try{btn.disabled=true;const ref=fs.doc(db,'homeworkSubmissions',`${id}_${session.uid}`);await fs.setDoc(ref,{homeworkId:id,userId:session.uid,studentName:session.name||session.email,studentEmail:session.email,answerText:ta.value.trim(),answerUrl:input.value.trim(),status:'submitted',submittedAt:fs.serverTimestamp(),submittedAtIso:new Date().toISOString()},{merge:true});submissions.set(id,{...(submissions.get(id)||{}),homeworkId:id,userId:session.uid,answerText:ta.value.trim(),answerUrl:input.value.trim(),status:'submitted',submittedAtIso:new Date().toISOString()});render();}catch(err){console.error(err);alert('Impossible d’envoyer le devoir. Vérifie Firestore.');}finally{btn.disabled=false;}}
try{[{db},fs]=await Promise.all([import('./firebase.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js')]);const [hSnap,sSnap]=await Promise.all([fs.getDocs(fs.collection(db,'homework')),fs.getDocs(fs.query(fs.collection(db,'homeworkSubmissions'),fs.where('userId','==',session.uid)))]);homeworks=hSnap.docs.map(d=>({id:d.id,...d.data()}));sSnap.docs.forEach(d=>{const x={id:d.id,...d.data()};submissions.set(x.homeworkId,x);});render();}catch(e){console.error(e);shell.innerHTML='<div class="dashboard-empty"><span>⚠️</span><h3>Devoirs indisponibles</h3><p>Vérifie les règles Firestore.</p></div>';}
})();
