let allQuestions=[],questions=[];const session=JSON.parse(localStorage.getItem('bl_session')||'null');const form=document.getElementById('quizForm'),container=document.getElementById('quizContainer'),result=document.getElementById('quizResult'),topicSelect=document.getElementById('quizTopic'),questionCount=document.getElementById('quizQuestionCount');

function relevantQuestion(q){
  if(!session)return false;
  if(q.level&&q.level!==session.level&&q.level!=='Tous')return false;
  if(session.level==='1ère')return !q.level||q.level==='1ère'||q.level==='Tous';
  return !q.section||q.section==='Toutes'||q.section==='Tronc commun'||q.section===session.section;
}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function render(){container.innerHTML=questions.map((q,idx)=>`<section class="quiz-card"><span class="eyebrow">${esc(q.topic||'Informatique')} · Question ${idx+1}</span><h3>${esc(q.question)}</h3><div class="quiz-options">${q.answers.map((a,i)=>`<label class="quiz-option"><input type="radio" name="q${idx}" value="${i}"><span>${esc(a)}</span></label>`).join('')}</div></section>`).join('');questionCount.textContent=`${questions.length} question${questions.length>1?'s':''}`;result.classList.add('hidden');}
function applyTopic(){const t=topicSelect.value;questions=t==='all'?allQuestions:allQuestions.filter(q=>q.topic===t);render();}
fetch('data/quiz.json').then(r=>r.json()).then(data=>{allQuestions=data.filter(relevantQuestion);[...new Set(allQuestions.map(q=>q.topic).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr')).forEach(t=>topicSelect.insertAdjacentHTML('beforeend',`<option value="${esc(t)}">${esc(t)}</option>`));if(!allQuestions.length){container.innerHTML=`<div class="dashboard-empty"><span>📝</span><h3>Aucun quiz pour ${esc(session?.level||'ton niveau')}</h3><p>Les quiz de ton niveau apparaîtront ici dès qu’ils seront disponibles.</p></div>`;questionCount.textContent='0 question';form.querySelector('button[type=submit]').classList.add('hidden');return;}applyTopic();}).catch(()=>container.innerHTML='<p>Impossible de charger le quiz.</p>');topicSelect.addEventListener('change',applyTopic);
async function syncQuizToFirebase(session,item){if(!session?.uid)return false;try{const [{db},{doc,setDoc,serverTimestamp}]=await Promise.all([import('./firebase.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js')]);await setDoc(doc(db,'quizResults',item.id),{userId:session.uid,title:item.title,topic:item.topic,score:item.score,raw:item.raw,totalQuestions:questions.length,createdAt:serverTimestamp()});return true;}catch(error){console.warn('Synchronisation quiz impossible',error);return false;}}
form.addEventListener('submit',async e=>{e.preventDefault();if(!questions.length)return;let score=0,answered=0;questions.forEach((q,idx)=>{const a=document.querySelector(`input[name="q${idx}"]:checked`);if(a){answered++;if(Number(a.value)===q.correct)score++;}});if(answered<questions.length){result.classList.remove('hidden');result.innerHTML='<h2>Quiz incomplet</h2><p>Réponds à toutes les questions avant de valider.</p>';return;}const pct=Math.round(score/questions.length*100),topic=topicSelect.value==='all'?'Général':topicSelect.value;result.classList.remove('hidden');result.innerHTML=`<h2>${pct}%</h2><p>${esc(topic)} · Score : ${score}/${questions.length}. ${pct>=70?'Bravo 🎉':'Continue à t’entraîner 💪'}</p><small id="quizSyncState">Enregistrement du résultat…</small>`;result.scrollIntoView({behavior:'smooth'});const session=JSON.parse(localStorage.getItem('bl_session')||'null');if(session){const now=new Date(),item={id:`${session.uid||'local'}_${now.getTime()}`,title:`Quiz ${topic}`,topic,score:pct,raw:`${score}/${questions.length}`,date:now.toISOString(),createdAt:now.toISOString()};item.level=session.level||'';item.section=session.section||'';const key=`bl_quiz_${session.email}`,history=JSON.parse(localStorage.getItem(key)||'[]');history.unshift(item);localStorage.setItem(key,JSON.stringify(history.slice(0,50)));const synced=await syncQuizToFirebase(session,item),state=document.getElementById('quizSyncState');if(state)state.textContent=synced?'☁️ Résultat synchronisé avec ton tableau de bord.':'💾 Résultat sauvegardé localement.';}});
