(async()=>{
const shell=document.getElementById('sessionsList'),count=document.getElementById('sessionCount');let items=[],mode='upcoming';
document.querySelector('.section-heading p')?.insertAdjacentHTML('afterend',`<div class="student-scope-badge">🎓 ${session.level}${session.level==='1ère'?' · Tronc commun':session.section?` · ${session.section}`:''}</div>`);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const session=JSON.parse(localStorage.getItem('bl_session')||'null');if(!session){location.href='login.html';return;}
function relevant(x){if(x.level&&x.level!==session.level&&x.level!=='Tous')return false;if(session.level==='1ère')return true;return !x.section||x.section==='Toutes'||x.section==='Tronc commun'||x.section===session.section;}
function dt(x){const d=new Date(x.startAtIso||x.dateTime||0);return Number.isNaN(d.getTime())?new Date(0):d;}
function render(){const now=new Date();const visible=items.filter(relevant).filter(x=>mode==='all'||dt(x)>=now).sort((a,b)=>dt(a)-dt(b));count.textContent=visible.length;if(!visible.length){shell.innerHTML='<div class="dashboard-empty"><span>📅</span><h3>Aucune séance programmée</h3><p>Le planning sera mis à jour au fur et à mesure des séances.</p></div>';return;}shell.innerHTML=visible.map(x=>{const d=dt(x),past=d<now;return `<article class="session-card ${past?'past':''}"><div class="session-date"><b>${d.toLocaleDateString('fr-FR',{day:'2-digit'})}</b><span>${d.toLocaleDateString('fr-FR',{month:'short'})}</span></div><div class="session-body"><div class="course-meta"><span>${esc(x.level||'Tous')}</span><span>${esc(x.section||'Toutes')}</span><span>T${esc(x.trimester||'1')}</span></div><h2>${esc(x.title||'Séance en ligne')}</h2><p>${esc(x.description||'')}</p><div class="session-time">🕒 ${d.toLocaleString('fr-FR',{weekday:'long',day:'2-digit',month:'long',hour:'2-digit',minute:'2-digit'})}</div>${x.meetUrl&&!past?`<a class="btn primary" href="${esc(x.meetUrl)}" target="_blank" rel="noopener">🎥 Rejoindre Google Meet</a>`:past?'<span class="student-status rejected">Séance terminée</span>':'<span class="student-status pending">Lien Meet à venir</span>'}</div></article>`}).join('');}
try{const [{db},{collection,getDocs}]=await Promise.all([import('./firebase.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js')]);const snap=await getDocs(collection(db,'sessions'));items=snap.docs.map(d=>({id:d.id,...d.data()}));render();}catch(e){console.error(e);shell.innerHTML='<div class="dashboard-empty"><span>⚠️</span><h3>Planning indisponible</h3><p>Vérifie les règles Firestore.</p></div>';}
document.querySelectorAll('[data-session-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-session-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.sessionFilter;render();}));
})();
